services:
  whatsapp:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: barberstudio_whatsapp
    ports:
      - "3000:3000"
    # Solo borra los locks, no recrea la carpeta
    command: >
      sh -c "rm -f /usr/src/app/sessions/barber-session/Singleton* &&
             node index.js"
    volumes:
      - ./sessions:/usr/src/app/sessions   # Sesiones persistentes en el host
    networks:
      - amagisa_net
    restart: unless-stopped

networks:
  amagisa_net:
    external: true
