# docker-compose.whatsapp.ymlgit

services:
  whatsapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: amagisa-whatsapp
    command: >
      sh -c "node index.js"
    deploy:
      resources:
        limits:
          memory: 600M
    environment:
      # Variables que Puppeteer usará para headless y shm
      PUPPETEER_HEADLESS: "true"
      PUPPETEER_DISABLE_DEV_SHM: "true"
    networks:
      - amagisa_net
    restart: unless-stopped

networks:
  amagisa_net:
    external: true
